apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: wikimedia-db
    type: database
spec:
  selector:
    matchLabels:
     app: wikimedia-db
  replicas: 1
  template:
    metadata:
      labels:
        app: wikimedia-db
        type: database
    spec:
      containers:
        - name: wikimedia-db
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_DATABASE
              value: mariadb
            - name: MYSQL_PASSWORD
              value: admin123
            - name: MYSQL_ROOT_PASSWORD
              value: admin1234
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: azure-managed-disk-pvc	
