apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  MARIADB_DATABASE: Yml0bmFtaV9tZWRpYXdpa2kK
  MARIADB_PASSWORD: Yml0bmFtaQo=
  MARIADB_USER: Ym5fbWVkaWF3aWtpCg==


